name: SEC Form 4 Tracker

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual triggering

# Prevent multiple runs from executing simultaneously
concurrency:
  group: sec-form4-tracker
  cancel-in-progress: false

permissions:
  contents: write  # Required to push changes

jobs:
  check-filings:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml
        
    - name: Run Form 4 checker
      run: python sec_form4_bot.py
      
    - name: Commit and push state file
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add last_filings.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update last filings state [skip ci]" && git pull --rebase origin main && git push)